/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazAgencia;

import BusquedaEmpleo.Agencia;
import BusquedaEmpleo.Candidato;
import BusquedaEmpleo.Direccion;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class AltaCandidato extends javax.swing.JFrame {

    private JFrame principal;
    private Candidato cand = null;
    private String path="",auxPath="";
    private int fuera;

   
    public AltaCandidato(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        ImageIcon imagen= new ImageIcon("src/fondo.jpg");
        jAgencia.setIcon(imagen);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAlta = new javax.swing.JButton();
        panelCandidato1 = new InterfazAgencia.PanelCandidato();
        jFoto = new javax.swing.JLabel();
        jImagen = new javax.swing.JButton();
        jAgencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar correo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jAlta.setText("Enviar");
        jAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaActionPerformed(evt);
            }
        });

        jImagen.setText("Añadir imagen");
        jImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImagen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAlta, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jImagen)
                        .addGap(192, 192, 192)))
                .addComponent(jAlta)
                .addGap(58, 58, 58))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-565)/2, (screenSize.height-646)/2, 565, 646);
    }// </editor-fold>//GEN-END:initComponents

    private void jAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaActionPerformed
        // Alta
        try{
            String nombre=panelCandidato1.getjNombre();
            String nif=panelCandidato1.getjNIF();
            String clave=panelCandidato1.getjListaClave();
            long telefono=panelCandidato1.getjTelefono();
            String ocupaciones=panelCandidato1.getjOcupaciones();
            String rango=panelCandidato1.getjRango();
            String via=panelCandidato1.getPanelDireccion1().getjVia();
            int numero=panelCandidato1.getPanelDireccion1().getjNumero();
            String piso=panelCandidato1.getPanelDireccion1().getjPisoLetra();
            String cp=panelCandidato1.getPanelDireccion1().getjCP();
            String localidad=panelCandidato1.getPanelDireccion1().getjLocalidad();
            String foto;
            if(fuera==0){
               foto=path;
            }else{
               foto=auxPath;
            }
            if(foto.equals("")){
                JOptionPane.showMessageDialog(this, "Introduzca una foto.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                throw new Exception();
            }
            //Añadimos al array
            Direccion d=new Direccion(via,numero,piso,localidad,cp);
            cand=new Candidato(nif,nombre,telefono,d,ocupaciones,rango,clave,foto);
            if (Agencia.altaCandidato(cand)) {
            JOptionPane.showMessageDialog(this, "E-mail enviado.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Agencia.guardarCandidatos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al enviar.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Excepción al enviar."+ e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jAltaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
        Agencia.guardarCandidatos();
    }//GEN-LAST:event_formWindowClosed

    private void jImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImagenActionPerformed
        // Este metodo solo sirve si el usuario se llama Jesus
        String aux="C:\\Users\\Jesus\\Documents\\NetBeansProjects\\PracticaFinal\\"; 
        //cadena que sirve para hacer la diferencia entre imagenes del proyecto y imagenes fuera de la carpeta
        String aux2;
        int auxLong;
        int ultimo;
        JFileChooser fc = new JFileChooser();//crea un selector de ficheros
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            /** si el valor del returnVal es el mismo que el que te da la opcion de "Aceptar" del selector
             entonces  se mete en codigo siguiente*/
            File file = fc.getSelectedFile(); //se consigue el archivo que se ha seleccionado
                path = file.getAbsolutePath(); //se consigue la ruta de acceso a ese archivo
                ultimo=path.length();//se consigue la longitud de esa cadena String
                if (ultimo>55){
                    /** lo que se va hacer a continuacion es diferenciar entre 
                     * las imagenes que se meten desde 
                     la carpeta del proyecto, y las que se meten desde fuera, 
                     * las que se meten desde una carpeta interna
                     del proyecto seran fijas, y las que se meten desde una carpeta
                     ajena no se veran si se cambia de ordenador, pero garantiza,
                     que al trasladar el programa funcione el cargador de imagenes*/
                    aux2=path.substring(0, 56);
                    if (aux2.equals(aux)){ // el codigo siguiente se hara si se mete desde la carpeta del proyecto
                        auxPath=path.substring(56,ultimo);
                        ImageIcon imagenes= new ImageIcon(auxPath);
                        jFoto.setIcon(imagenes);
                        fuera=1;
                    }
                }
                else{// si la imagen es cargada desde una carpeta ajena del poryecto
                    ImageIcon imagenes= new ImageIcon(path);
                    jFoto.setIcon(imagenes);
                    fuera=0;
                }
                
              
        } else {
            fc.setEnabled(false);
        }    
    }//GEN-LAST:event_jImagenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAgencia;
    private javax.swing.JButton jAlta;
    private javax.swing.JLabel jFoto;
    private javax.swing.JButton jImagen;
    private InterfazAgencia.PanelCandidato panelCandidato1;
    // End of variables declaration//GEN-END:variables
}
