/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazAgencia;

import BusquedaEmpleo.Agencia;
import BusquedaEmpleo.Candidato;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class ConsultaCandidatos extends javax.swing.JFrame {

        private JFrame principal;
        private ArrayList<Candidato> candaux;
        private ListIterator li;
        private Candidato objcand;
        
    public ConsultaCandidatos(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        panelCandidato1.desactivar();
        consultarTodo();
        ImageIcon imagen= new ImageIcon("src/fondo.jpg");
        jAgencia.setIcon(imagen);
        this.setVisible(true);
    }
    
     /** Consulta los candidatos del ArrayList para su presentación */
    private void consultarTodo() {
        try {
            //referenciamos al ArrayList de Agencia
            candaux= Agencia.getCandidatos();
         
            //creamos el iterador sobre el ArrayList
            li = candaux.listIterator();
            //si no hay candidatos...
            if (candaux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                jSig.setEnabled(false);
                jAnt.setEnabled(false);
                jBorrar.setEnabled(false);
                return;
            } else {
                jSig.setEnabled(true);
                jAnt.setEnabled(true);
                jBorrar.setEnabled(true);
            }
            //presentamos la primera oferta
            if (li.hasNext()) {
                objcand = (Candidato) li.next();
            }
            if (objcand != null) {
                presenta(objcand);
            } else {
                JOptionPane.showMessageDialog(this, "No hay candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            return;
        }
    }//fin consultarTodo

    /** Presenta los datos de un candidato en el panel de datos */
    private void presenta(Candidato cand) {
        panelCandidato1.setjNombre(cand.getNombre());
        panelCandidato1.setjListaClave(cand.getListaClave());
        panelCandidato1.setjOcupaciones(cand.getOcupaciones());
        panelCandidato1.setjRango(cand.getRangoSalarial());
        panelCandidato1.setjTelefono(cand.getTelefono());
        panelCandidato1.setjNIF(cand.getNIF());
        panelCandidato1.getPanelDireccion1().setjCP(cand.getDireccion().getCodigoPostal());
        panelCandidato1.getPanelDireccion1().setjLocalidad(cand.getDireccion().getLocalidad());
        panelCandidato1.getPanelDireccion1().setjNumero(cand.getDireccion().getNumero());
        panelCandidato1.getPanelDireccion1().setjPisoLetra(cand.getDireccion().getPisoLetra());
        panelCandidato1.getPanelDireccion1().setjVia(cand.getDireccion().getNombreVia());
        ImageIcon imagenes= new ImageIcon(cand.getFoto());
        jFoto.setIcon(imagenes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCandidato1 = new InterfazAgencia.PanelCandidato();
        jAnt = new javax.swing.JButton();
        jSig = new javax.swing.JButton();
        jBorrar = new javax.swing.JButton();
        jFoto = new javax.swing.JLabel();
        jAgencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Candidatos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jAnt.setText("Anterior");
        jAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAntActionPerformed(evt);
            }
        });

        jSig.setText("Siguiente");
        jSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSigActionPerformed(evt);
            }
        });

        jBorrar.setText("BORRAR");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAnt)
                        .addGap(83, 83, 83)
                        .addComponent(jBorrar)
                        .addGap(75, 75, 75)
                        .addComponent(jSig))
                    .addComponent(panelCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBorrar)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSig, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAnt))))
                .addGap(31, 31, 31)
                .addComponent(panelCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-597)/2, (screenSize.height-661)/2, 597, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void jSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSigActionPerformed
        // TODO add your handling code here:
        try{
            if (li.hasNext()) {
               objcand = (Candidato) li.next();//se obtiene el candidato siguiente
               if (objcand != null) {
                    presenta(objcand);// si hay datos en ese objeto candidato se muestran en la pantalla
               }  
           } else {
              JOptionPane.showMessageDialog(this, "No hay mas candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
    }//GEN-LAST:event_jSigActionPerformed

    private void jAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAntActionPerformed
        // TODO add your handling code here:
        try{
            if (li.hasPrevious()) {
               objcand = (Candidato) li.previous();//se obtiene el candidato anterior
               if (objcand != null) {
                    presenta(objcand);// si hay datos en ese objeto candidato se muestran en la pantalla
               }  
           } else {
              JOptionPane.showMessageDialog(this, "No hay mas candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
    }//GEN-LAST:event_jAntActionPerformed

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed
        // TODO add your handling code here:        
     if(Agencia.borraCandidato(objcand)){
        li.remove();
        JOptionPane.showMessageDialog(this, "Candidato borrado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, " Error: - Candidato no encontrado - ", "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
    //mostramos el elemento siguiente o anterior
    if (li.hasNext()) {
        objcand = (Candidato) li.next();
        if (objcand != null) {
            presenta(objcand);
        } else {
            JOptionPane.showMessageDialog(this, "No hay candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    } else if (li.hasPrevious()) {
        objcand = (Candidato) li.previous();
        if (objcand != null) {
            presenta(objcand);
        } else {
            JOptionPane.showMessageDialog(this, "No hay candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }else {
        JOptionPane.showMessageDialog(this, "No hay candidatos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        this.formWindowClosed(null);
        this.setVisible(!true);
    }
        Agencia.guardarCandidatos();
    }//GEN-LAST:event_jBorrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAgencia;
    private javax.swing.JButton jAnt;
    private javax.swing.JButton jBorrar;
    private javax.swing.JLabel jFoto;
    private javax.swing.JButton jSig;
    private InterfazAgencia.PanelCandidato panelCandidato1;
    // End of variables declaration//GEN-END:variables
}
