/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazAgencia;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Jesus
 */
public class pruebafoto extends javax.swing.JFrame {

    /**
     * Creates new form pruebafoto
     */
    private String path="",auxPath="";
    private int fuera;
    public pruebafoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jFoto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String aux="C:\\Users\\Jesus\\Documents\\NetBeansProjects\\PracticaFinal\\"; 
        //cadena que sirve para hacer la diferencia entre imagenes del proyecto y imagenes fuera de la carpeta
        String aux2;
        int auxLong;
        int ultimo;
        JFileChooser fc = new JFileChooser();//crea un selector de ficheros
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            /** si el valor del returnVal es el mismo que el que te da la opcion de "Aceptar" del selector
             entonces  se mete en codigo siguiente*/
            File file = fc.getSelectedFile(); //se consigue el archivo que se ha seleccionado
                path = file.getAbsolutePath(); //se consigue la ruta de acceso a ese archivo
                ultimo=path.length();//se consigue la longitud de esa cadena String
                if (ultimo>55){
                    /** lo que se va hacer a continuacion es diferenciar entre 
                     * las imagenes que se meten desde 
                     la carpeta del proyecto, y las que se meten desde fuera, 
                     * las que se meten desde una carpeta interna
                     del proyecto seran fijas, y las que se meten desde una carpeta
                     ajena no se veran si se cambia de ordenador, pero garantiza,
                     que al trasladar el programa funcione el cargador de imagenes*/
                    aux2=path.substring(0, 56);
                    if (aux2.equals(aux)){ // el codigo siguiente se hara si se mete desde la carpeta del proyecto
                        auxPath=path.substring(56,ultimo);
                        ImageIcon imagenes= new ImageIcon(auxPath);
                        jFoto.setIcon(imagenes);
                        fuera=1;
                    }
                }
                else{// si la imagen es cargada desde una carpeta ajena del poryecto
                    ImageIcon imagenes= new ImageIcon(path);
                    jFoto.setIcon(imagenes);
                    fuera=0;
                }
                
              
        } else {
            fc.setEnabled(false);
        }
        if(fuera==0){
            System.out.println("no fuera"+path);
            
        }else{
            System.out.println("si fuera"+auxPath);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebafoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebafoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebafoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebafoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebafoto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jFoto;
    // End of variables declaration//GEN-END:variables
}
