/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Concesionario.AlmacenadoVehiculos;
import Concesionario.Cliente;
import Concesionario.RegistroVentas;
import Concesionario.RegistrosPersonas;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro.barquin
 */
public class Entrar extends javax.swing.JFrame {

    //atributos necesarios
    private JFrame principal;
    private AlmacenadoVehiculos almacen;
    private RegistrosPersonas persona;
    private RegistroVentas venta;

    /**
     * Creates new form Entrar
     */
    //constructor con lo recibido desde la ventana principal
    public Entrar(Principal ventana, AlmacenadoVehiculos almacen, RegistrosPersonas persona, RegistroVentas venta) {
        initComponents();
        principal = ventana;            //referencia a la ventana principal
        this.almacen = almacen;
        this.persona = persona;
        this.venta = venta;
        principal.setVisible(false);    //oculta la ventana principal
        this.setVisible(true);          //muestra esta ventana
        setLocationRelativeTo(null);    //centra el jframe en el medio de la pantalla
        ImageIcon imagen = new ImageIcon("src/fondo.jpg");  //crea la imagen
        jLabel4.setIcon(imagen);        //muestra la imagen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Entrada Vehiculos de ocasion");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //al cerrar la ventana hace visible la principal
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //boton entrar
        if (jTextField1.getText().equals("") || String.valueOf(jPasswordField2.getPassword()).equals("")) {     //si no se a completado los campos error
            JOptionPane.showMessageDialog(this, "No se han rellenado todos los campos o estan mal escritos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mesnaje de que faltan campos por rellenar
        } else {
            String usuario = jTextField1.getText();                                         //obtiene el texto del campo username
            int pw = Integer.valueOf(String.valueOf(jPasswordField2.getPassword()));        //obtiene el texto del campo password
            if ("admin".equals(usuario)) {                                                  //en caso de que sea igual a admin continua si no salta al else
                if (pw == 1111) {                                                           //si ademas el pw es igual a 1111 entra como admin
                    jTextField1.setText("");                                                //limpia los campos
                    jPasswordField2.setText("");
                    VentanaAdmin s = new VentanaAdmin(this, almacen, venta);                //crea la ventana de entrada como admin y se pasa esta ventana el registro almacen y venta
                }else {
                    JOptionPane.showMessageDialog(this, "Usuario o Pasword Incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {                                                                        //no se a compludo que el user name es igual a admin   
                if (persona.contiene(usuario)) {                                            //si el user name esta en el registro de personas continua
                    if (persona.pw(usuario) == pw) {                                        //si esta la persona y el pw coincide con el suyo continua
                        Cliente us = persona.obtenerpersona(usuario);                       //se obtiene el cliente en cuestion
                        jTextField1.setText("");                                            //se limpian los campos
                        jPasswordField2.setText("");
                        VentanaUsuario s = new VentanaUsuario(this, almacen, venta, us);    //se crea la entrada como usuario se pasa la ventana el registro almacen venta y la persona que a entrado
                    } else {
                        JOptionPane.showMessageDialog(this, "Usuario o Pasword Incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);      //mensajes de error
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o Pasword Incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
