/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Concesionario.AlmacenadoVehiculos;
import Concesionario.Cliente;
import Concesionario.RegistroVentas;
import Concesionario.Vehiculo;
import Interface.Entrar;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro.barquin
 */
//clase ventan de usuario
public class VentanaUsuario extends javax.swing.JFrame {

    //atributios
    private JFrame vUsuario;
    private RegistroVentas venta;
    private AlmacenadoVehiculos almacen;
    private ArrayList<Vehiculo> vehi;
    private Vehiculo vehicu;
    private Cliente cli;

    /**
     * Creates new form VentanaUsuario
     */
    //contructor con los datos recibidos desde entrar
    public VentanaUsuario(Entrar ventana, AlmacenadoVehiculos almacen, RegistroVentas venta, Cliente cli) {
        initComponents();
        vUsuario = ventana;            //referencia a la ventana anterior
        this.almacen = almacen;
        this.venta = venta;
        this.cli = cli;
        vUsuario.setVisible(false);    //oculta la ventana anterior
        this.setVisible(true);          //muestra esta ventana
        setLocationRelativeTo(null);    //centra el jframe en el medio de la pantalla
        ImageIcon imagen = new ImageIcon("src/fondo.jpg");   //creamos la imagen
        jLabel5.setIcon(imagen);        //mostramos la imagen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Usuario En");

        jLabel2.setText("Busqueda");

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //se hace visible la ventana entrar al cerrar esta
        vUsuario.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //boton buscar
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("")) {     //si no se a completado los campos error
            JOptionPane.showMessageDialog(this, "No se han rellenado todos los campos o estan mal escritos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mesnaje de que faltan campos por rellenar
        } else {
            String model = jTextField2.getText();                     //se obtiene el modelo con lo escrito el la textfiel modelo
            String mark = jTextField1.getText();                      //se obtiene la marca con lo escrito el la textfiel marca
            vehi = almacen.obtenervehiculo();                         //se obtiene un arraylist con todos los vehiculos almacenazos
            ArrayList<Vehiculo> aux = new ArrayList<Vehiculo>();      //se crea un arraylist ausiliar para guardar los que coinciden
            for (int i = 0; i < vehi.size(); i++) {                   //se va comprobando uno a unos
                vehicu = vehi.get(i);                                 //se obtiene el vehiculo del arraylist
                if (vehicu.getmodelo().equalsIgnoreCase(model)) {     //se verifica el modelo
                    if (vehicu.getmarca().equalsIgnoreCase(mark)) {   //se verifica la marca
                        aux.add(vehicu);                              //si es asi se almacena
                    }
                }
            }
            VentanaBusqueda a = new VentanaBusqueda(this, aux, almacen, venta, cli); //al terminar se crea la ventana busqueda pasando esta ventana el registro almacen venta, el cliente que lo busca y el arrylist con los vehiculos que coinciden
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
