/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Concesionario.AlmacenadoVehiculos;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro.barquin
 */
//clase ventana bajas
public class VentanaBajas extends javax.swing.JFrame {

    //atributos
    private JFrame vBajas;
    private AlmacenadoVehiculos almacen;

    /**
     * Creates new form VentanaBajas
     */
    //constructor con los datos recibidos de la ventana admin
    public VentanaBajas(VentanaAdmin ventana, AlmacenadoVehiculos almacen) {
        initComponents();
        vBajas = ventana;            //referencia a la ventana admin
        this.almacen = almacen;
        vBajas.setVisible(false);    //oculta la ventana admin
        this.setVisible(true);          //muestra esta ventana
        setLocationRelativeTo(null);    //centra el jframe en el medio de la pantalla
        ImageIcon imagen = new ImageIcon("src/fondo.jpg");   //creamos la imagen
        jLabel3.setIcon(imagen);        //mostramos la imagen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Bajas Vehiculos");

        jLabel2.setText("Mtraiculas del Vehiculo a dar de baja:");

        jButton1.setText("Baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //al pulsar el boton cerrar se muestra la ventana admin 
        vBajas.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //al pulsar el boton baja
        if (jFormattedTextField1.getText().equals("       ")) {     //si no se a completado los campos error
            JOptionPane.showMessageDialog(this, "No se han rellenado todos los campos o estan mal escritos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mesnaje de que faltan campos por rellenar
        } else {
            boolean res = almacen.bajaVehiculo(jFormattedTextField1.getText());  //se obtiene la matricula y se da de baja el vehiculo recibiendo la respuesta
            if (res == false) {                                         //si el resultado es false la matricula no existe
                JOptionPane.showMessageDialog(this, "No hay Vehiculos con esa matriucla", "Error", JOptionPane.INFORMATION_MESSAGE);    //mensaje que no existe
            } else {                                                    //si es true
                JOptionPane.showMessageDialog(this, "Retirado del registro", "Mensaje", JOptionPane.INFORMATION_MESSAGE);               //mensaje de vehiculo eliminado
                jFormattedTextField1.setText("");                                                                                                //se vacia el campo
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
