/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

//importaciones necesarias
import Concesionario.AlmacenadoVehiculos;
import Concesionario.Cliente;
import Concesionario.RegistroVentas;
import Concesionario.Vehiculo;
import Concesionario.Venta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author pedro.barquin
 */
//clase ventana busqueda 
public class VentanaBusqueda extends javax.swing.JFrame {

    //atributos necesarios
    private JFrame vBusqueda;
    private ArrayList<Vehiculo> veh;
    private ListIterator li;
    private Vehiculo vehicul;
    private Vehiculo vehiculaux;
    private AlmacenadoVehiculos almac;
    private RegistroVentas ventad;
    private Venta vendido;
    private Cliente cli;
    private double fina = 0;

    /**
     * Creates new form VentanaCompra
     */
    //constructor con los parametro recibidos desde la ventana usuario
    public VentanaBusqueda(VentanaUsuario ventana, ArrayList<Vehiculo> veh, AlmacenadoVehiculos almac, RegistroVentas ventad, Cliente cli) {
        initComponents();
        vBusqueda = ventana;            //referencia a la ventana anterior
        this.veh = veh;
        this.almac = almac;
        this.ventad = ventad;
        this.cli = cli;
        vBusqueda.setVisible(false);    //oculta la ventana anterior
        this.setVisible(true);          //muestra esta ventana
        setLocationRelativeTo(null);    //centra el jframe en el medio de la pantalla
        ImageIcon imagen = new ImageIcon("src/fondo.jpg");  //se crea la imagen
        jLabel7.setIcon(imagen);        //se muestra
        consultarbusqueda();            //llamada a mostrar la informacion 
    }

    private void consultarbusqueda() {
        try {
            //creamos el iterador sobre el ArrayList
            li = veh.listIterator();
            //si no hay vehiculos...
            if (veh.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay vehiculos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mesaje de que no hay vehiculos
                jButton3.setEnabled(false);             //se desactivan los botones
                jButton4.setEnabled(false);
                jButton1.setEnabled(false);
                return;
            } else {                                    //si hubiera vehiculos
                jButton2.setEnabled(true);              //se activan los botones
                jButton1.setEnabled(true);
            }
            //presentamos los vehiculos
            if (li.hasNext()) {
                vehicul = (Vehiculo) li.next();         //se obtiene el vehiculo
            }
            if (vehicul != null) {                      //si no es nulo
                presentar(vehicul);                     //se muestra pasando el vehiculo
            } else {                                    //si es nulo no hay mas vehiculos
                JOptionPane.showMessageDialog(this, "No hay mas vehiculos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mesnaje de no hay mas
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);      //mensaje de error
            System.out.println("Error: " + e.toString());
            return;
        }
    }

    //metodo que muestra en los campos los valores del vehiculo pasado
    public void presentar(Vehiculo veh) {
        jTextField1.setText(veh.getmatricula());
        jTextField2.setText(veh.getmarca());
        jTextField3.setText(veh.getmodelo());
        jTextField4.setText(Double.toString(veh.getpotencia()));
        jTextField5.setText(veh.getcolor());
        jTextField6.setText(Integer.toString(veh.getanofabricacion()));
        jTextField7.setText(Integer.toString(veh.getkilometros()));
        jTextField8.setText(Double.toString(veh.getprecio()));
        jTextField15.setText(veh.tipoVehiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Vehiculos encotrados en la busqueda");

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricula");

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel10.setText("Kilometros");

        jLabel6.setText("Potencia");

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Color");

        jLabel9.setText("Año fabricacion");

        jButton4.setText("Anterior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Precio");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel3.setText("Vehiculo");

        jLabel12.setText("C.V");

        jLabel13.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButton4)
                                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGap(70, 70, 70))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(68, 68, 68)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //se hace visible la ventana usuario
        vBusqueda.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //al pulsar volcer se cierra y termina esta centana y se llama a cerrar
        formWindowClosed(null);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //boton siguiente
        try {
            if (li.hasNext()) {                 //proxima
                vehicul = (Vehiculo) li.next(); //se obtiene el vehiculo siguiente
                if (vehicul != null) {
                    presentar(vehicul); // si hay datos en ese objeto vehiculo se muestran en la pantalla
                }
            } else {                    //si no hay mas posibles es que no hay mas vehiculos    
                JOptionPane.showMessageDialog(this, "No hay mas vehiculos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mensaje de que no hay mas
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);          //mesanje de error
            System.out.println("Error: " + e.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //boton de anterior
        try {
            if (li.hasPrevious()) {                     //anterior
                vehicul = (Vehiculo) li.previous();     //se obtiene el vehiculo anterior
                if (vehicul != null) {
                    presentar(vehicul); // si hay datos en ese objeto vehiculo se muestran en la pantalla
                }
            } else {                    //si no hay mas posibles es que no hay mas vehiculos    
                JOptionPane.showMessageDialog(this, "No hay mas vehiculos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);   //mensaje de que no hay mas

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);          //mesanje de error
            System.out.println("Error: " + e.toString());

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        //boton de comprar
        if (jTextField1.getText() != "") {                                      //si el campo no esta vacio se continua
            String ma = jTextField1.getText();                                  //se obtiene la matricula del vehiculo
            vehiculaux = almac.obtenervehiculo(ma);                             //con l amtricula se obtiene el vehiculo

            JPanel panel = new JPanel();                                        //se crea un nuevo panel
            JLabel label = new JLabel("Inserte Datos de administrador:");       //mensaje del panel
            JTextField user = new JTextField(10);                               //cuadro de texto del panel
            JPasswordField pass = new JPasswordField(4);                        //cuadro de contraseña del panel
            panel.add(label);                                                   //se añaden al panel
            panel.add(user);
            panel.add(pass);
            String[] options = new String[]{"OK", "Cancel"};                    //opciones del panel
            int option = JOptionPane.showOptionDialog(null, panel, "The title", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);   //se muestra y se recoje el resultado
            if (option == 0) //si presionado OK 
            {
                String password = String.valueOf(pass.getPassword());           //se obtiene la contraseña
                String usuario = user.getText();                                //se obtiene el usurname
                if ("admin".equals(usuario)) {                                  //si el username es igual a admin
                    if ("1111".equals(password)) {                              //si el pw es igual a 1111
                        String qw = "Empleado";                                 //valores aux
                        String wq = "Familiar";
                        if (cli.getrelacionConcesionario().equalsIgnoreCase(qw)) {              //si el cliente es empleado
                            fina = (vehiculaux.getprecio() - (vehiculaux.getprecio() * 0.25));  //se asigna precion final de empleado
                        } else if (cli.getrelacionConcesionario().equalsIgnoreCase(wq)) {       //si el cliente es familiar 
                            fina = (vehiculaux.getprecio() - (vehiculaux.getprecio() * 0.10));  //se asina precio final familiar
                        } else {
                            fina = vehiculaux.getprecio();
                        }
                        //se crea el objeto venta con toda la informacion de usuario y del vehiculo
                        vendido = new Venta(cli.getnombreApellido(), cli.getcodigoUsuario(), cli.getdni(), cli.getrelacionConcesionario(), vehiculaux.getmatricula(), vehiculaux.getmarca(), vehiculaux.getmodelo(), vehiculaux.getcolor(), Integer.toString(vehiculaux.getanofabricacion()), Integer.toString(vehiculaux.getkilometros()), fina, vehiculaux.tipoVehiculo(), Double.toString(vehiculaux.getpotencia()));
                        try {
                            ventad.insertarventa(vendido);                      //se mete en registroventas e imprimir factura
                        } catch (IOException ex) {
                            Logger.getLogger(VentanaBusqueda.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        almac.bajaVehiculo(vehiculaux.getmatricula());          //eliminar el vehiculo del almacen
                        JOptionPane.showMessageDialog(this, "Vehiculo Vendido", "Mensaje", JOptionPane.INFORMATION_MESSAGE);    //mostrar mensaje de vendido                        
                        this.setVisible(false);                                                                                 //se cierra la ventana 
                        this.dispose();                                                                                         //salir                      
                    } else {
                        JOptionPane.showMessageDialog(this, "No tienes permisos de administrador", "Error", JOptionPane.INFORMATION_MESSAGE);   //mensaje por si no se a insertado correctamente los datos de admin
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes permisos de administrador", "Error", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
